In [1]:
import matplotlib.pyplot as plt 
import metapack as mp
import pandas as pd
import numpy as np
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline

In [2]:
from savReaderWriter import SavReader

!pwd

/Users/eric/proj/virt-proj/data-project/sdrdl-data-projects/cornell-social-survey/cornell.edu-cnss-2017/notebooks

In [17]:
# The variable KRq1, Number of Dogs, has a duplicate label problem when the file is converted with StatTransfer; 
# StatTransfer seperates out the number from the text "dogs", and pandas
# interprets this as multiple labels with the value "dogs". The easiest way to
# handle this is to remove the variable. 

_1 = pd.read_stata('../data/cnss2017.dta', convert_categoricals=False)
columns = list(_1.columns)
columns.remove('KRq1')

df = pd.read_stata('../data/cnss2017.dta', columns = columns)

df.head()

,caseid,survid,timezone,state,msa,msc,censusr,censusd,cbsamsa,cbsamcsa,...,RACE_E,numraces,relig,church,hhince,hhinc50k,hhincu,hhinco,hhinc,gender
0,80007,80007,C,TX,2920,1,3,7,3,5,...,No,1.0,No religion / Atheist / Agnostic,A few times a year,NaN,"$50,000 or over",NaN,"$150,000 or more","$150,000 or more",Male
1,80027,80027,C,AL,,5,3,6,5,1,...,No,1.0,Protestant,A few times a year,NaN,"$50,000 or over",NaN,"50 to under $75,000","50 to under $75,000",Female
2,80029,80029,C,LA,5560,3,3,7,3,5,...,No,1.0,Catholic,A few times a year,196000,NaN,NaN,NaN,"$150,000 or more",Male
3,80037,80037,C,IN,,5,2,3,5,1,...,No,1.0,No religion / Atheist / Agnostic,Never,75000,NaN,NaN,NaN,"75 to under $100,000",Male
4,80041,80041,C,MO,3760,1,2,4,1,5,...,No,1.0,No religion / Atheist / Agnostic,Never,60000,NaN,NaN,NaN,"50 to under $75,000",Female

In [26]:
itr = pd.read_stata('file.dta', iterator=True)
itr.variable_labels()

FileNotFoundError: [Errno 2] No such file or directory: 'file.dta'

0       True
1       True
2       True
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10      True
11     False
12      True
13      True
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25      True
26      True
27     False
28      True
29     False
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978     True
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986     True
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999     True
Length: 1000, dtype: bool